#CAVM_SAI_URL = https://github.com/XPliant/OpenXPS/raw/c26aea6a7098936ab3692e148238d73fa8962585/SAI
CAVM_SAI_LOCAL = /sonic/platform/cavium/cavm_sdk

CAVM_XPNET_DEB = xp80-Pcie-Endpoint.deb
#$(CAVM_XPNET_DEB)_URL = $(CAVM_SAI_URL)/netdev/$(CAVM_XPNET_DEB)
$(CAVM_XPNET_DEB)_PATH = $(CAVM_SAI_LOCAL)
SONIC_COPY_DEBS += $(CAVM_XPNET_DEB)
#SONIC_ONLINE_DEBS += $(CAVM_XPNET_DEB)
