# thrift package

KEXEC-TOOLS_VERSION = 2.0.14
KEXEC-TOOLS_VERSION_FULL = $(KEXEC-TOOLS_VERSION)-1

KEXEC-TOOLS = kexec-tools_$(KEXEC-TOOLS_VERSION_FULL)_$(SONiC_ARCH).deb
$(KEXEC-TOOLS)_SRC_PATH = $(SRC_PATH)/kexec-tools
SONIC_MAKE_DEBS += $(KEXEC-TOOLS)
